apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-deployment
  labels:
    app: my-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: my-nodejs-container
        image: adarshnode/my-node-app:01
        ports:
        - containerPort: 3000
